name: typled
description: The package to parse typled text content.
version: 0.0.2
repository: https://github.com/erickzanardo/typled

environment:
  sdk: ^3.5.1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
