name: typled_editor
description: "Typled Editor."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flame: ^1.19.0
  flame_fire_atlas: ^1.5.4
  typled:
    path: ../typled
  nes_ui: ^0.20.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  image_path: ../icon.png
  windows:
    generate: true
    image_path: ../icon.png
    icon_size: 48
  macos:
    generate: true
    image_path: ../icon.png
