name: typled_cli
description: A sample command-line application with basic argument parsing.
version: 0.0.1
repository: https://github.com/erickzanardo/typled

executables:
  typled:

environment:
  sdk: ^3.5.1

dependencies:
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
